# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qrCodeViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qrCodeViewer(object):
    def setupUi(self, qrCodeViewer):
        qrCodeViewer.setObjectName("qrCodeViewer")
        qrCodeViewer.resize(626, 500)
        qrCodeViewer.setStyleSheet("background-color: rgb(212, 238, 255);")
        self.qr = QtWidgets.QLabel(qrCodeViewer)
        self.qr.setGeometry(QtCore.QRect(160, 30, 300, 300))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.qr.setFont(font)
        self.qr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.qr.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);")
        self.qr.setScaledContents(True)
        self.qr.setAlignment(QtCore.Qt.AlignCenter)
        self.qr.setObjectName("qr")
        self.verticalLayoutWidget = QtWidgets.QWidget(qrCodeViewer)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 360, 621, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(qrCodeViewer)
        QtCore.QMetaObject.connectSlotsByName(qrCodeViewer)

    def retranslateUi(self, qrCodeViewer):
        _translate = QtCore.QCoreApplication.translate
        qrCodeViewer.setWindowTitle(_translate("qrCodeViewer", "Form"))
        self.qr.setText(_translate("qrCodeViewer", "QR Code não encontrado"))
        self.label_2.setText(_translate("qrCodeViewer", "Conecte o Whatsapp com o Qr"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    qrCodeViewer = QtWidgets.QWidget()
    ui = Ui_qrCodeViewer()
    ui.setupUi(qrCodeViewer)
    qrCodeViewer.show()
    sys.exit(app.exec_())
